$$
d_1=\sqrt{(p_{1s}-p_{1c_1})^2+\dots+(p_{ns}-p_{nc_1})^2}
$$
$$
\vdots
$$
$$
d_m=\sqrt{(p_{1s}-p_{1c_m})^2+\dots+(p_{ns}-p_{nc_m})^2}
$$
$$
E(x)=d_1x_1+d_2x_2+\dots+d_{m}x_{m}
$$
|変数|内容|
|-|-|
|$p_1$|パラメータ1 : レベル(仮)|
|$p_2$|パラメータ2 : 必要時間(仮)|
|$p_3$|パラメータ3 : 人気度(仮)|
|$\vdots$|$\vdots$|
|$p_n$|パラメータn|
|$\bm{S}$|観測点(学習者)の座標($p_{1s},p_{2s},...,p_{ns}$)|
|$\bm{C}_1$|教材1の座標($p_{1c_1},p_{2c_1},...,p_{nc_1}$)|
|$\vdots$|$\vdots$|
|$\bm{C}_m$|教材$m$の座標($p_{1c_m},p_{2c_m},...,p_{nc_m}$)|
|$k$|選択する教材の数|
|$d_m$|観測点$\bm{S}$から教材$m$の座標へのユークリッド距離|


$$
E(x)=\sum_{i=1}^{m}d_{i}x_{i}+\lambda  \left(
\sum_{i=1}^{m}x_{i}-k\right) ^2
$$

In [16]:
import numpy as np
import random

# 観測点の座標。要素数はNparaと合わせる
s = [0, 0, 0]   # 観測点の座標
mu, sigma = 0, 1
Npara = 3  # 特徴量空間のパラメータ数（特徴量の数）
Nmater = 10  # 教材の数
x = {}
# for i in range(Nmater):
#     x[i] = [random.gauss(mu, sigma) for i in range(Npara)]
#     # print(x[i])

# print(x)


# mat = np.zeros([Nmater, Npara])
# for i in range(Nmater):
#     mat[i, :] = x[i]
# print(mat)

for i in range(Nmater):
    x[i] = [random.gauss(mu, sigma) for i in range(Npara)]

mat = np.array(list(x.values()))
print(mat)

{0: [0.871284276372944, -0.8216187020155453, -0.6245123921138398], 1: [-0.47183692150313955, 1.287229816744363, -0.32094740736111066], 2: [-0.08713409055339974, -0.10759334822807241, -0.11071428795831866], 3: [-2.3405264233480465, -0.37177770787059766, 0.28594895504566764], 4: [1.5852287141419388, 0.26475087015111315, 0.879640323587529], 5: [-1.3157939849101814, -0.14961875734721433, -0.9224209547843403], 6: [-1.3397544669513688, -1.2132638225924706, 1.5484291312651601], 7: [0.6146227394812938, 1.3605257970037303, 1.8810311974305876], 8: [-0.29908191796924793, -0.32015039221351665, 0.37761765717753615], 9: [-0.26133388773386684, 1.642541755720242, 1.2703028079561822]}
[[ 0.87128428 -0.8216187  -0.62451239]
 [-0.47183692  1.28722982 -0.32094741]
 [-0.08713409 -0.10759335 -0.11071429]
 [-2.34052642 -0.37177771  0.28594896]
 [ 1.58522871  0.26475087  0.87964032]
 [-1.31579398 -0.14961876 -0.92242095]
 [-1.33975447 -1.21326382  1.54842913]
 [ 0.61462274  1.3605258   1.8810312 ]
 [-0.299081

In [18]:
type(mat)

numpy.ndarray

In [9]:
dist = {}
# for i in range(Nmater):
#     dist[i] = euclidean_distance(s, mat[i, :])
#     print(dist[i])
for i,li in enumerate(mat):
    dist[i] = np.linalg.norm(li-s)
    print(dist[i])

2.2157310346517263
1.7305241328540668
3.745473693186627
1.6616318633788987
1.2249538976623562
0.8272232755034503
1.002742606058126
0.06818095556988181
1.5520105046268866
0.6050472673095196


In [11]:
# distを対角行列化

new_dist = np.array([])  # 新しい配列を初期化

for i in range(Nmater):
    new_dist = np.append(new_dist, dist[i])
dist = new_dist
dist_mat = np.diag(dist)
print(dist_mat)

[[2.21573103 0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         1.73052413 0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         3.74547369 0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         1.66163186 0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         1.2249539  0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.82722328
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.00274261 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.06818096 0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         1.5520105  0.        ]
 [0.         0.         0.   

In [12]:

#罰則項の作成
N=Nmater

#選択する教材数
K=3
def create_penalty(N,K):
    P = np.zeros([N,N])
    for i in range(N):
        for j in range(N):
            P[i,j] = 1
    for i in range(N):
        P[i,i] = P[i,i] - 2*K
    return P
QUBO = create_penalty(N,K)

In [14]:
QUBO

array([[-5.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1., -5.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., -5.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., -5.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., -5.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., -5.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., -5.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1., -5.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -5.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -5.]])

In [ ]:
#QUBO行列を生成し、Dwaveマシーンで計算
pip install dwave-ocean-sdk

In [ ]:
token = "XXXXXX"
import numpy as np
from dwave.system import DWaveSampler, EmbeddingComposite

dw_sampler = DWaveSampler(solver='Advantage_system6.1', token=token)
sampler = EmbeddingComposite(dw_sampler)
lamda=1

QUBO = dist_mat + lamda * create_penalty(N,K)
sampleset = sampler.sample_qubo(QUBO, num_reads=100)
